### ISSUE TITLE
(fili Dec17) Why some elements are out of the container?

### ISSUE THREAD

**Issue by AlphaBud75** [KPCommittee2023/TSM-Monogatari#41]
go to preview link (open inincognito mode) :
https://kpcommittee2023.github.io/TSM-Monogatari/

I am making the layout for main/home page.
https://www.figma.com/file/VZOZq1ULJQDs4rnSFuqzWl/two-sides-of-the-moon?type=design&node-id=260-303&mode=design

I want to see this
![image](https://github.com/KPCommittee2023/TSM-Monogatari/assets/100396124/a567ba12-06bb-422c-a148-4c8c3a2905aa)

but the overflow is off
![image](https://github.com/KPCommittee2023/TSM-Monogatari/assets/100396124/76569598-f037-46c5-940a-1ba8c837a4ef)

Can you adjust the html/css at F12 mode and find the fix for "hidding overflowing elements"?
Just find the fix. dont edit the source. I am still working on the source.

code is at main.js for reference.

**Comment by sunfili-side-up** [comment]
Just have to explicitly add overflow: hidden to this specific div highlighted in the screenshot below
<img width="784" alt="image" src="https://github.com/KPCommittee2023/TSM-Monogatari/assets/127279415/ae73b2e9-8b29-41fd-a6fe-666ca7ea42f0">
<img width="956" alt="image" src="https://github.com/KPCommittee2023/TSM-Monogatari/assets/127279415/91568811-3337-42bf-b52f-7d9b609571c8">

**Comment by sunfili-side-up** [comment]
maybe the orange one that was already in the code was not working due to spacing?? not sure

**Comment by sunfili-side-up** [comment]
oh nvm i just checked and it still doesn't work if you change it from main.js still but setting the overflow: hidden instead in the parent div seems to work?

**Comment by AlphaBud75** [comment]
fixed. thank you
